[package]
name = "tornado-common"
version = "0.0.0"
edition = "2021"

[features]
default = ["real", "app"]
app = []
mcu = []
real = []
fake = []

[dependencies]
flatty = { path = "../flatty", default-features = false }
atomic-traits = { path = "../atomic-traits" }
