[package]
name = "tornado-common"
version = "0.0.0"
edition = "2021"

[features]
default = ["real", "app"]
app = []
mcu = []
real = []
fake = []

[dependencies]
atomic-traits = { path = "../atomic-traits" }
derive_more = "0.99.17"

[dependencies.flatty]
path = "../flatty"
default-features = false
