[package]
name = "tornado-mcu"
version = "0.0.0"
edition = "2021"

[lib]
name = "user"
crate-type = ["staticlib"]

[profile.release]
lto = true
#opt-level = "z"

[features]
default = ["real"]
real = ["freertos", "lazy_static/spin_no_std"]
emul = ["flatty-io", "flatty/std", "timeout-readwrite"]
panic = []

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
ringbuf = { version = "0.3.2", default-features = false }
flatty = { path = "../../flatty", default-features = false }
flatty-io = { path = "../../flatty/io", optional = true }
timeout-readwrite = { version = "0.3.3", optional = true }
ux = { version = "0.1.5", default-features = false }
indenter = "0.3.3"
portable-atomic = { version = "1.0.1" }

[dependencies.derive_more]
version = "0.99.17"
default-features = false
features = ["from"]

[dependencies.freertos]
package = "freertos-rust"
path = "../freertos/freertos-rust"
default-features = false
features = ["sync", "time", "interrupt"]
optional = true

[dependencies.common]
package = "tornado-common"
path = "../../common"
