[package]
name = "tornado-mcu"
version = "0.0.0"
edition = "2021"

[lib]
name = "user"
crate-type = ["staticlib", "lib"]

[profile.release]
lto = true
#opt-level = "z"

[features]
default = ["real"]
real = ["ustd/backend-freertos", "lazy_static/spin_no_std"]
fake = [
    "ustd/backend-std",
    "flatty-io",
    "flatty/std",
    "timeout-readwrite",
    "common/fake",
]
panic = ["ustd/panic"]

[dependencies]
lazy_static = { version = "1.4.0" }
ringbuf = { version = "0.3.2", default-features = false }
flatty = { path = "../../flatty", default-features = false }
flatty-io = { path = "../../flatty/io", optional = true }
timeout-readwrite = { version = "0.3.3", optional = true }
ux = { version = "0.1.5", default-features = false }
indenter = "0.3.3"
portable-atomic = "1.0.1"
atomic-traits = { path = "../../atomic-traits" }

[dependencies.derive_more]
version = "0.99.17"
default-features = false
features = ["from", "deref", "deref_mut"]

[dependencies.ustd]
path = "../ustd"
default-features = false

[dependencies.common]
package = "tornado-common"
path = "../../common"
