[package]
name = "tornado-mcu"
version = "0.1.0"
edition = "2021"

[lib]
name = "user"
crate-type = ["staticlib"]

[features]
default = ["emul"]
real = ["panic", "freertos", "lazy_static/spin_no_std"]
emul = ["flatty-io", "flatty/std"]
panic = []

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
flatty = { path = "../../flatty", default-features = false }
flatty-io = { path = "../../flatty/io", optional = true }

[dependencies.freertos]
package = "freertos-rust"
path = "../freertos/freertos-rust"
default-features = false
features = ["sync"]
optional = true

[dependencies.common]
package = "tornado-common"
path = "../../common"
