image: agerasev/debian-psc

test:
  stage: test
  only:
    - merge_requests
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python3 -u -m manage all.build
    - python3 -u -m manage all.test_host
