image: debian

build:
  stage: build
  only:
    - merge_requests
  before_script:
    - apt-get update
    - apt-get -y install git g++ cmake make python3 python3-pip libgtest-dev libzmq3-dev
    - pip3 install -r requirements.txt
  script:
    - python3 -m manage all.build
  artifacts:
    paths:
      - target

test:
  stage: test
  only:
    - merge_requests
  before_script:
    - apt-get update
    - apt-get -y install python3 python3-pip libgtest-dev libzmq3-dev
    - pip3 install -r requirements.txt
  script:
    - python3 -m manage all.test_host
